- name: Install MySQL
  apt:
    name: mysql-server
    state: present
    update_cache: yes
  become: yes

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes

- name: Install PyMySQL
  apt:
    name: python3-pymysql
    state: present
  become: yes



