- name: Install required packages
  apt:
    name:
      - docker.io
      - python3-pip
    state: present
    update_cache: yes

- name: Docker  is running
  service:
    name: docker
    state: started
    enabled: true

- name: Pull MinIO Docker image
  docker_image:
    name: minio/minio
    source: pull
  ignore_errors: yes

- name: MinIO image exists
  docker_image:
    name: minio/minio
    source: local

- name: Run MinIO container
  docker_container:
    name: minio
    image: minio/minio
    state: started
    restart_policy: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    env:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "123"
    command: server /data --console-address ":9001"
    volumes:
      - /mnt/data/minio:/data



